### ISSUE TITLE
runns daemon should renew its socket file after executed more than once

### ISSUE THREAD

**Issue by phantomcraft** [sh1r4s3/runns#1]
When I execute runns daemon (the binary one) for the first time, it works ok, but when it doesn't start after the first execution.

For running again I have to delete the folder in which the socket is:

**rm -rf /var/run/runns/**

I think this behavior should be corrected.

**Comment by sh1r4s3** [comment]
@phantomcraft thank you for reporting the issue!

**Comment by phantomcraft** [comment]
@sh1r4s3 

It's ok!

I sent en e-mail to you with a suggestion for a similar program.
